'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace LoggingServiceReference
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="BatchInfo", [Namespace]:="http://schemas.datacontract.org/2004/07/LoggingWFAgentService"),  _
     System.SerializableAttribute()>  _
    Partial Public Class BatchInfo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BatchClassNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BatchNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CreationDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CurrentModuleNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumberOfLoosePagesField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BatchClassName() As String
            Get
                Return Me.BatchClassNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BatchClassNameField, value) <> true) Then
                    Me.BatchClassNameField = value
                    Me.RaisePropertyChanged("BatchClassName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BatchName() As String
            Get
                Return Me.BatchNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BatchNameField, value) <> true) Then
                    Me.BatchNameField = value
                    Me.RaisePropertyChanged("BatchName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CreationDate() As Date
            Get
                Return Me.CreationDateField
            End Get
            Set
                If (Me.CreationDateField.Equals(value) <> true) Then
                    Me.CreationDateField = value
                    Me.RaisePropertyChanged("CreationDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CurrentModuleName() As String
            Get
                Return Me.CurrentModuleNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CurrentModuleNameField, value) <> true) Then
                    Me.CurrentModuleNameField = value
                    Me.RaisePropertyChanged("CurrentModuleName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NumberOfLoosePages() As Integer
            Get
                Return Me.NumberOfLoosePagesField
            End Get
            Set
                If (Me.NumberOfLoosePagesField.Equals(value) <> true) Then
                    Me.NumberOfLoosePagesField = value
                    Me.RaisePropertyChanged("NumberOfLoosePages")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DocumentInfo", [Namespace]:="http://schemas.datacontract.org/2004/07/LoggingWFAgentService"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DocumentInfo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FieldInfoListField() As LoggingServiceReference.FieldInfo
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FormTypeNameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FieldInfoList() As LoggingServiceReference.FieldInfo()
            Get
                Return Me.FieldInfoListField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FieldInfoListField, value) <> true) Then
                    Me.FieldInfoListField = value
                    Me.RaisePropertyChanged("FieldInfoList")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FormTypeName() As String
            Get
                Return Me.FormTypeNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FormTypeNameField, value) <> true) Then
                    Me.FormTypeNameField = value
                    Me.RaisePropertyChanged("FormTypeName")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="FieldInfo", [Namespace]:="http://schemas.datacontract.org/2004/07/LoggingWFAgentService"),  _
     System.SerializableAttribute()>  _
    Partial Public Class FieldInfo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IndexFieldNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IndexFieldValueField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IndexFieldName() As String
            Get
                Return Me.IndexFieldNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IndexFieldNameField, value) <> true) Then
                    Me.IndexFieldNameField = value
                    Me.RaisePropertyChanged("IndexFieldName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IndexFieldValue() As String
            Get
                Return Me.IndexFieldValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IndexFieldValueField, value) <> true) Then
                    Me.IndexFieldValueField = value
                    Me.RaisePropertyChanged("IndexFieldValue")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="LoggingServiceReference.ILoggingService")>  _
    Public Interface ILoggingService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILoggingService/LogBatchInfo", ReplyAction:="http://tempuri.org/ILoggingService/LogBatchInfoResponse")>  _
        Function LogBatchInfo(ByVal oBatchInfo As LoggingServiceReference.BatchInfo) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILoggingService/LogBatchInfo", ReplyAction:="http://tempuri.org/ILoggingService/LogBatchInfoResponse")>  _
        Function LogBatchInfoAsync(ByVal oBatchInfo As LoggingServiceReference.BatchInfo) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILoggingService/LogDocumentInfo", ReplyAction:="http://tempuri.org/ILoggingService/LogDocumentInfoResponse")>  _
        Sub LogDocumentInfo(ByVal oDocumentInfoList() As LoggingServiceReference.DocumentInfo, ByVal nBatchId As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILoggingService/LogDocumentInfo", ReplyAction:="http://tempuri.org/ILoggingService/LogDocumentInfoResponse")>  _
        Function LogDocumentInfoAsync(ByVal oDocumentInfoList() As LoggingServiceReference.DocumentInfo, ByVal nBatchId As Integer) As System.Threading.Tasks.Task
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ILoggingServiceChannel
        Inherits LoggingServiceReference.ILoggingService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class LoggingServiceClient
        Inherits System.ServiceModel.ClientBase(Of LoggingServiceReference.ILoggingService)
        Implements LoggingServiceReference.ILoggingService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function LogBatchInfo(ByVal oBatchInfo As LoggingServiceReference.BatchInfo) As Integer Implements LoggingServiceReference.ILoggingService.LogBatchInfo
            Return MyBase.Channel.LogBatchInfo(oBatchInfo)
        End Function
        
        Public Function LogBatchInfoAsync(ByVal oBatchInfo As LoggingServiceReference.BatchInfo) As System.Threading.Tasks.Task(Of Integer) Implements LoggingServiceReference.ILoggingService.LogBatchInfoAsync
            Return MyBase.Channel.LogBatchInfoAsync(oBatchInfo)
        End Function
        
        Public Sub LogDocumentInfo(ByVal oDocumentInfoList() As LoggingServiceReference.DocumentInfo, ByVal nBatchId As Integer) Implements LoggingServiceReference.ILoggingService.LogDocumentInfo
            MyBase.Channel.LogDocumentInfo(oDocumentInfoList, nBatchId)
        End Sub
        
        Public Function LogDocumentInfoAsync(ByVal oDocumentInfoList() As LoggingServiceReference.DocumentInfo, ByVal nBatchId As Integer) As System.Threading.Tasks.Task Implements LoggingServiceReference.ILoggingService.LogDocumentInfoAsync
            Return MyBase.Channel.LogDocumentInfoAsync(oDocumentInfoList, nBatchId)
        End Function
    End Class
End Namespace
